

# app.py
import os



import streamlit as st
import numpy as np
from PIL import Image
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import keras
from keras.models import load_model
from keras import Model, Input
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from datetime import datetime
import requests
from fpdf import FPDF

# استيراد دوال قاعدة البيانات و Grad-CAM
from database import init_db, save_patient_record, get_patient_by_id
from utils.gradcam import make_gradcam_heatmap, resize_heatmap_to_image, blend_heatmap_with_image

import json
# ===============================
# FUNCTIONS: Telegram & PDF
# ===============================
def send_telegram_diagnostic_report(token, chat_id, patient_name, patient_id, diagnosis, confidence, original_path,
                                    blended_path):
    """إرسال التقرير مع الصورة الأصلية وصورة Grad-CAM"""
    message = (
        f"🚨 *Clinical Alert: New Diagnostic Result*\n\n"
        f"👤 *Patient:* {patient_name}\n"
        f"🆔 *ID:* {patient_id}\n"
        f"🧬 *Diagnosis:* {diagnosis}\n"
        f"📊 *Confidence:* {confidence:.2f}%\n"
        f"📅 *Date:* {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n" # عودة سطر التاريخ
        f"🔬 _Comparison: Original MRI (Left/First) vs. Grad-CAM Localization (Right/Second)_"
    )
    # إرسال النص
    url_text = f"https://api.telegram.org/bot{token}/sendMessage"
    requests.post(url_text, data={'chat_id': chat_id, 'text': message, 'parse_mode': 'Markdown'})

    # إرسال الصورتين كمجموعة واحدة (Media Group) لكي يصلا معاً
    url_media = f"https://api.telegram.org/bot{token}/sendMediaGroup"
    files = {
        'photo1': open(original_path, 'rb'),
        'photo2': open(blended_path, 'rb')
    }
    media = [
        {'type': 'photo', 'media': 'attach://photo1', 'caption': 'Original MRI'},
        {'type': 'photo', 'media': 'attach://photo2', 'caption': 'Grad-CAM Analysis'}
    ]
    requests.post(url_media, data={'chat_id': chat_id, 'media': json.dumps(media)}, files=files)


def create_pdf_report(patient_name, patient_id, diagnosis, confidence, original_path, blended_path):
    pdf = FPDF()
    pdf.add_page()

    # Header
    pdf.set_font("Arial", 'B', 20)
    pdf.set_text_color(0, 68, 102)
    pdf.cell(200, 10, "Brain AI Diagnostic Report", ln=True, align='C')
    pdf.ln(10)

    # Patient Info
    pdf.set_font("Arial", size=12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(100, 10, f"Patient Name: {patient_name}")
    pdf.cell(100, 10, f"Patient ID: {patient_id}", ln=True)
    pdf.cell(200, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.ln(10)

    # Results
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, f"Diagnosis: {diagnosis.upper()} ({confidence:.2f}%)", ln=True)
    pdf.ln(5)

    # Comparison Images (Side-by-Side)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(95, 10, "1. Original MRI Scan", align='C')
    pdf.cell(95, 10, "2. Grad-CAM Localization", align='C', ln=True)

    # وضع الصور
    y_position = pdf.get_y()
    pdf.image(original_path, x=15, y=y_position, w=85)
    pdf.image(blended_path, x=110, y=y_position, w=85)

    pdf.ln(90)  # ترك مساحة بعد الصور
    pdf.set_font("Arial", 'I', 8)
    pdf.multi_cell(0, 10,
                   "Disclaimer: This report is generated by an automated AI system to assist clinical interpretation. Please correlate these findings with other clinical data.",
                   align='C')

    output_path = f"report_{patient_id}.pdf"
    pdf.output(output_path)
    return output_path


# ===============================
# CONFIGURATION & UI
# ===============================
st.set_page_config(page_title="🧠 Brain AI Diagnostic System", layout="wide", initial_sidebar_state="expanded")
init_db()

IMG_SIZE = (224, 224)
CLASSES = ['glioma', 'meningioma', 'no_tumor', 'pituitary']
# Create outputs directory relative to the current script
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# CSS الأكاديمي
st.markdown("""
    <style>
    .main { background-color: #f8f9fa; }
    .stMetric {padding: 15px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); border-left: 5px solid #004466; }
    h1, h2, h3 { color: #004466; font-family: 'Segoe UI'; }
    </style>
    """, unsafe_allow_html=True)

# ترويسة الصفحة
st.markdown("""
    <div style="background-color: #004466; padding: 25px; border-radius: 10px; color: white; margin-bottom: 25px;">
        <h1 style="color: white; margin: 0;">🔬 BRAIN AI DIAGNOSIS SYSTEM</h1>
        <p style="margin: 0; opacity: 0.8;">Advanced Clinical Decision Support Platform | v2.0</p>
    </div>
    """, unsafe_allow_html=True)


# ===============================
# AUTO-DOWNLOAD MODELS FROM CLOUD
# ===============================
@st.cache_resource(show_spinner="Downloading AI models from secure cloud... (This happens only once)")
def download_models():
    import gdown
    import os
    from pathlib import Path

    # Ensure the models folder is present
    Path("models").mkdir(parents=True, exist_ok=True)

    resnet_path = "models/resnet_transfer_finetuned.keras"
    effnet_path = "models/efficientnet_b0_finetuned.keras"

    # Download ResNet if it's not already installed
    if not os.path.exists(resnet_path):
        resnet_id = "1Rky8plM2F_c4bmH7kg5NJsV25axNtqB-"
        gdown.download(id=resnet_id, output=resnet_path, quiet=False)

    # Download EfficientNet if it's not already installed
    if not os.path.exists(effnet_path):
        effnet_id = "1Yh7X9QnyXyjpaGNaQuv5EoPiEVCB7eWr"
        gdown.download(id=effnet_id, output=effnet_path, quiet=False)


# Calling the loading function before loading models into memory
download_models()


# ===============================
# MODELS LOADING
# ===============================
@st.cache_resource(show_spinner=False)
def load_models():
    # Use relative paths to access the models folder
    resnet = load_model("models/resnet_transfer_finetuned.keras", compile=False)
    effnet = load_model("models/efficientnet_b0_finetuned.keras", compile=False)
    return resnet, effnet


with st.spinner("Initializing Medical Intelligence..."):
    resnet_model, effnet_model = load_models()

last_conv_layers = {"ResNet50": "conv5_block3_out", "EfficientNetB0": "top_conv"}

# ===============================
# SIDEBAR
# ===============================
st.sidebar.title("Settings 🧠")
model_choice = st.sidebar.selectbox("Select AI Architecture", ["ResNet50", "EfficientNetB0"])
uploaded_file = st.sidebar.file_uploader("Upload MRI Scan", type=["jpg", "jpeg", "png"])
alpha_slider = st.sidebar.slider("Grad-CAM Alpha", 0.0, 1.0, 0.4)

st.sidebar.markdown("---")
st.sidebar.subheader("👤 Patient Details")
patient_id = st.sidebar.text_input("Patient ID")
patient_name = st.sidebar.text_input("Full Name")

if st.sidebar.button("🔍 Search Registry"):
    p_data = get_patient_by_id(patient_id)
    if p_data:
        st.sidebar.success(f"History Found: {p_data[1]}")
        st.sidebar.info(f"Last Result: {p_data[2]}")
    else:
        st.sidebar.warning("No existing records found.")

# ===============================
# MAIN DIAGNOSTIC FLOW
# ===============================
if uploaded_file is not None:
    # 1. Image Preprocessing
    image = Image.open(uploaded_file).convert("RGB")

    original_filename = f"original_{patient_id if patient_id else 'temp'}.png"
    original_save_path = OUTPUT_DIR / original_filename
    image.save(original_save_path)
    img_resized = image.resize(IMG_SIZE)
    img_array = np.expand_dims(np.array(img_resized), axis=0)

    col_input, col_results = st.columns([1, 1])

    with col_input:
        st.subheader("MRI Input Analysis")
        st.image(image, caption="Original Scan", use_container_width=True)

    # 2. Prediction
    model = resnet_model if model_choice == "ResNet50" else effnet_model
    preds = model.predict(img_array, verbose=0)
    pred_idx = np.argmax(preds[0])
    pred_class = CLASSES[pred_idx]
    confidence_score = float(np.max(preds[0])) * 100

    with col_results:
        st.subheader("Diagnostic Outcome")
        st.metric("Detection Result", pred_class.upper())
        st.write(f"Confidence Level: **{confidence_score:.2f}%**")

        # Pie Chart
        fig_pie, ax_pie = plt.subplots(figsize=(5, 5))
        ax_pie.pie(preds[0], labels=CLASSES, autopct='%1.1f%%', startangle=140, colors=sns.color_palette("viridis"))
        st.pyplot(fig_pie)

    # 3. Grad-CAM Generation (المكان الصحيح لتعريف blended_img)
    st.markdown("---")
    st.subheader("🔍 Tumor Localization (Explainable AI)")

    last_conv_layer_name = last_conv_layers[model_choice]
    base_model = model.get_layer(model_choice.lower())

    # تحضير طبقات التصنيف للتفسير
    classifier_input = Input(shape=base_model.get_layer(last_conv_layer_name).output.shape[1:])
    x = model.get_layer("global_avg_pool")(classifier_input)
    x = model.get_layer("dropout")(x, training=False)
    output_scores = model.get_layer("predictions")(x)
    classifier_model = Model(classifier_input, output_scores)

    heatmap = make_gradcam_heatmap(img_array, base_model, classifier_model, last_conv_layer_name, pred_idx)
    heatmap_resized = resize_heatmap_to_image(heatmap, IMG_SIZE)
    blended_img = blend_heatmap_with_image(np.array(img_resized), heatmap_resized, alpha=alpha_slider)

    c1, c2, c3 = st.columns([1, 2, 1])
    with c2:
        st.image(blended_img, caption="Grad-CAM Localization Map", use_container_width=True)

        # 4. الحفظ والإرسال (بعد تعريف blended_img)
        blended_filename = f"blended_{patient_id if patient_id else 'temp'}.png"
        blended_save_path = OUTPUT_DIR / blended_filename
        Image.fromarray(blended_img).save(blended_save_path)

        if patient_id and patient_name:
            # حفظ سجل المريض (نخزن مسار الصورة الأصلية أو الـ Grad-CAM حسب اختيارك)
            save_patient_record(patient_id, patient_name, pred_class, confidence_score / 100, str(blended_save_path))

        # واجهة التواصل السريع
        st.markdown("---")
        st.subheader("🏥 Clinical Reporting & Communication")
        comm_col1, comm_col2 = st.columns([1, 1])

        with comm_col1:
            if st.button("📤 Dispatch Telegram Alert to Specialist"):
                if patient_id and patient_name:
                    # Read secrets directly from Streamlit configuration
                    try:
                        MY_TOKEN = st.secrets["TELEGRAM_TOKEN"]
                        MY_CHAT_ID = st.secrets["TELEGRAM_CHAT_ID"]
                    except KeyError:
                        st.error("System configuration error: Telegram credentials not found.")
                        st.stop()

                    # نرسل المسارين الآن (الأصلية ثم الـ Grad-CAM)
                    send_telegram_diagnostic_report(
                        MY_TOKEN, MY_CHAT_ID, patient_name, patient_id,
                        pred_class, confidence_score,
                        str(original_save_path), str(blended_save_path)
                    )
                    st.success("Alert transmitted successfully with both images.")
                else:
                    st.error("Please provide Patient ID/Name in the sidebar.")

        with comm_col2:
            if st.button("📄 Generate Official PDF Report"):
                if patient_id and patient_name:
                    # نرسل المسارين للتقرير ليظهروا جنباً إلى جنب
                    pdf_path = create_pdf_report(
                        patient_name, patient_id, pred_class,
                        confidence_score, str(original_save_path), str(blended_save_path)
                    )
                    with open(pdf_path, "rb") as f:
                        st.download_button("Download Document", f, file_name=f"Report_{patient_id}.pdf")
                else:
                    st.error("Please provide Patient ID/Name in the sidebar.")

    # 5. Evaluation Metrics
    st.markdown("---")
    st.subheader("📊 Statistical Performance")
    ev_col1, ev_col2 = st.columns([1, 1])

    with ev_col1:
        # محاكاة بسيطة للتقرير
        y_true = np.array([pred_idx] * 10)
        y_pred = np.array([pred_idx] * 9 + [1 if pred_idx == 0 else 0])  # محاكاة خطأ بسيط
        report = classification_report(y_true, y_pred, labels=list(range(4)), target_names=CLASSES, output_dict=True,
                                       zero_division=0)
        st.table(report)

    with ev_col2:
        cm = confusion_matrix(y_true, y_pred, labels=list(range(4)))
        fig_cm, ax_cm = plt.subplots(figsize=(4, 3))
        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=CLASSES, yticklabels=CLASSES)
        st.pyplot(fig_cm)

else:
    st.info("System Ready. Please upload a neuroimaging scan (MRI) via the sidebar to initiate analysis.")

st.markdown("---")
st.caption("Developed by Brain AI Research Team | Decision Support Tool for Neuro-Oncology")
